// Types:
import { Doctor } from "@/types/doctors.types";

export const DOCTORS: Doctor[] = [
  {
    doctorId: "dr-sarah-ahmed",
    name: "Dr. Sarah Ahmed",
    specialty: "Cardiologist",
    image: "/assets/images/doctors/dr-sarah-ahmed.jpg",
    experience: 12,
    bio: "Dr. Sarah Ahmed is a board-certified cardiologist with over 12 years of experience diagnosing and treating cardiovascular conditions. She specializes in preventive cardiology, heart failure management, and interventional procedures.",
    education: [
      "MD, Cairo University",
      "Residency in Internal Medicine, Kasr Al Ainy Hospital",
      "Fellowship in Cardiology, Egyptian Heart Institute",
    ],
    certifications: [
      "Egyptian Board of Cardiology",
      "European Society of Cardiology",
    ],
    languages: ["English", "Arabic"],
    consultationFee: 500,
    rating: 4.9,
    reviewCount: 248,
    availableToday: true,
    services: [
      "Cardiac Consultation",
      "ECG",
      "Echocardiography",
      "Hypertension Management",
      "Heart Failure Treatment",
    ],
  },

  {
    doctorId: "dr-omar-hassan",
    name: "Dr. Omar Hassan",
    specialty: "Dermatologist",
    image: "/assets/images/doctors/dr-omar-hassan.jpg",
    experience: 9,
    bio: "Dr. Omar Hassan is a dermatologist specializing in medical and cosmetic dermatology. He focuses on acne treatment, skin conditions, hair loss, and advanced cosmetic procedures.",
    education: [
      "MD, Ain Shams University",
      "Dermatology Residency, Ain Shams University Hospitals",
    ],
    certifications: [
      "Egyptian Board of Dermatology",
      "American Academy of Dermatology Member",
    ],
    languages: ["English", "Arabic", "French"],
    consultationFee: 400,
    rating: 4.8,
    reviewCount: 186,
    availableToday: true,
    services: [
      "Skin Consultation",
      "Acne Treatment",
      "Hair Loss Treatment",
      "Laser Treatment",
      "Cosmetic Dermatology",
    ],
  },

  {
    doctorId: "dr-mariam-ali",
    name: "Dr. Mariam Ali",
    specialty: "Pediatrician",
    image: "/assets/images/doctors/dr-mariam-ali.jpg",
    experience: 15,
    bio: "Dr. Mariam Ali is a highly experienced pediatrician dedicated to providing comprehensive medical care for infants, children, and adolescents. She has a special interest in childhood development and preventive care.",
    education: [
      "MD, Alexandria University",
      "Pediatric Residency, Alexandria University Hospital",
      "Pediatric Fellowship, Children's Cancer Hospital",
    ],
    certifications: [
      "Egyptian Board of Pediatrics",
      "Member of the Royal College of Paediatrics",
    ],
    languages: ["English", "Arabic"],
    consultationFee: 450,
    rating: 4.9,
    reviewCount: 312,
    availableToday: false,
    services: [
      "Child Consultation",
      "Newborn Care",
      "Vaccination",
      "Growth & Development",
      "Child Nutrition",
    ],
  },

  {
    doctorId: "dr-youssef-mahmoud",
    name: "Dr. Youssef Mahmoud",
    specialty: "Orthopedic Surgeon",
    image: "/assets/images/doctors/dr-youssef-mahmoud.jpg",
    experience: 11,
    bio: "Dr. Youssef Mahmoud is an orthopedic surgeon with extensive experience in sports injuries, joint problems, and minimally invasive orthopedic procedures. He works with athletes and active patients of all ages.",
    education: [
      "MD, Mansoura University",
      "Orthopedic Surgery Residency, Mansoura University Hospital",
      "Sports Medicine Fellowship, Barcelona Sports Medicine Center",
    ],
    certifications: [
      "Egyptian Board of Orthopedic Surgery",
      "International Society of Arthroscopy Member",
    ],
    languages: ["English", "Arabic", "Spanish"],
    consultationFee: 600,
    rating: 4.7,
    reviewCount: 174,
    availableToday: true,
    services: [
      "Orthopedic Consultation",
      "Sports Injury Treatment",
      "Joint Pain Treatment",
      "Arthroscopy",
      "Fracture Management",
    ],
  },

  {
    doctorId: "dr-nour-ibrahim",
    name: "Dr. Nour Ibrahim",
    specialty: "Neurologist",
    image: "/assets/images/doctors/dr-nour-ibrahim.jpg",
    experience: 10,
    bio: "Dr. Nour Ibrahim is a neurologist specializing in the diagnosis and treatment of neurological disorders, including migraines, epilepsy, neuropathy, and movement disorders.",
    education: [
      "MD, Cairo University",
      "Neurology Residency, Kasr Al Ainy Hospital",
      "Clinical Neurology Fellowship, King’s College London",
    ],
    certifications: [
      "Egyptian Board of Neurology",
      "European Academy of Neurology Member",
    ],
    languages: ["English", "Arabic"],
    consultationFee: 550,
    rating: 4.8,
    reviewCount: 201,
    availableToday: false,
    services: [
      "Neurology Consultation",
      "Migraine Treatment",
      "Epilepsy Management",
      "Neuropathy Treatment",
      "Nerve Testing",
    ],
  },

  {
    doctorId: "dr-layla-mostafa",
    name: "Dr. Layla Mostafa",
    specialty: "Gynecologist",
    image: "/assets/images/doctors/dr-layla-mostafa.jpg",
    experience: 14,
    bio: "Dr. Layla Mostafa is an experienced obstetrician and gynecologist providing comprehensive women's healthcare, from routine examinations and prenatal care to reproductive health and minimally invasive procedures.",
    education: [
      "MD, Ain Shams University",
      "OB/GYN Residency, Ain Shams University Hospital",
      "Women's Health Fellowship, University College London",
    ],
    certifications: [
      "Egyptian Board of Obstetrics & Gynecology",
      "Royal College of Obstetricians and Gynaecologists Member",
    ],
    languages: ["English", "Arabic"],
    consultationFee: 500,
    rating: 4.9,
    reviewCount: 267,
    availableToday: true,
    services: [
      "Gynecology Consultation",
      "Prenatal Care",
      "Women's Health Checkup",
      "Ultrasound",
      "Reproductive Health",
    ],
  },

  {
    doctorId: "dr-ahmed-khaled",
    name: "Dr. Ahmed Khaled",
    specialty: "Internal Medicine",
    image: "/assets/images/doctors/dr-ahmed-khaled.jpg",
    experience: 13,
    bio: "Dr. Ahmed Khaled is an experienced internal medicine specialist with a focus on diabetes, thyroid disorders, metabolic conditions, and preventive healthcare. He takes a comprehensive approach to managing chronic conditions and improving long-term health.",
    education: [
      "MD, Cairo University",
      "Internal Medicine Residency, Kasr Al Ainy Hospital",
      "Endocrinology Fellowship, Cairo University Hospitals",
    ],
    certifications: [
      "Egyptian Board of Internal Medicine",
      "American Association of Clinical Endocrinology Member",
    ],
    languages: ["English", "Arabic"],
    consultationFee: 450,
    rating: 4.8,
    reviewCount: 229,
    availableToday: true,
    services: [
      "Internal Medicine Consultation",
      "Diabetes Management",
      "Thyroid Treatment",
      "Cholesterol Management",
      "Health Checkup",
    ],
  },

  {
    doctorId: "dr-reem-samir",
    name: "Dr. Reem Samir",
    specialty: "Ophthalmologist",
    image: "/assets/images/doctors/dr-reem-samir.jpg",
    experience: 8,
    bio: "Dr. Reem Samir is an ophthalmologist specializing in comprehensive eye care, corneal conditions, vision correction, and refractive surgery. She is passionate about providing personalized treatment plans for patients of all ages.",
    education: [
      "MD, Alexandria University",
      "Ophthalmology Residency, Alexandria University Hospital",
      "Cornea Fellowship, Moorfields Eye Hospital",
    ],
    certifications: [
      "Egyptian Board of Ophthalmology",
      "European Society of Ophthalmology Member",
    ],
    languages: ["English", "Arabic", "French"],
    consultationFee: 450,
    rating: 4.9,
    reviewCount: 193,
    availableToday: true,
    services: [
      "Eye Examination",
      "Vision Testing",
      "Corneal Treatment",
      "LASIK Consultation",
      "Dry Eye Treatment",
    ],
  },

  {
    doctorId: "dr-reem-fathy",
    name: "Dr. Reem Fathy",
    specialty: "Dentist",
    image: "/assets/images/doctors/dr-reem-fathy.jpg",
    experience: 7,
    bio: "Dr. Reem Fathy is a cosmetic and restorative dentist focused on creating healthy, natural-looking smiles. She specializes in veneers, teeth whitening, restorative procedures, and preventive dental care.",
    education: [
      "BDS, Cairo University",
      "Diploma in Cosmetic Dentistry, University of Barcelona",
      "Advanced Restorative Dentistry Program, Cairo University",
    ],
    certifications: [
      "Egyptian Dental Syndicate",
      "International Association for Dental Research Member",
    ],
    languages: ["English", "Arabic"],
    consultationFee: 350,
    rating: 4.7,
    reviewCount: 142,
    availableToday: true,
    services: [
      "Dental Consultation",
      "Teeth Whitening",
      "Dental Veneers",
      "Dental Cleaning",
      "Restorative Dentistry",
    ],
  },

  {
    doctorId: "dr-mostafa-nabil",
    name: "Dr. Mostafa Nabil",
    specialty: "Urologist",
    image: "/assets/images/doctors/dr-mostafa-nabil.jpg",
    experience: 16,
    bio: "Dr. Mostafa Nabil is a senior urologist with extensive experience in urinary tract conditions, kidney stones, prostate health, and men's health. He has a particular interest in minimally invasive urological procedures.",
    education: [
      "MD, Mansoura University",
      "Urology Residency, Mansoura University Hospital",
      "Urology Fellowship, University of Milan",
    ],
    certifications: [
      "Egyptian Board of Urology",
      "European Association of Urology Member",
    ],
    languages: ["English", "Arabic", "Italian"],
    consultationFee: 550,
    rating: 4.9,
    reviewCount: 278,
    availableToday: true,
    services: [
      "Urology Consultation",
      "Kidney Stone Treatment",
      "Prostate Evaluation",
      "Urinary Tract Treatment",
      "Men's Health",
    ],
  },

  {
    doctorId: "dr-salma-younis",
    name: "Dr. Salma Younis",
    specialty: "Endocrinologist",
    image: "/assets/images/doctors/dr-salma-younis.jpg",
    experience: 10,
    bio: "Dr. Salma Younis is an endocrinologist specializing in hormonal and metabolic disorders. She provides comprehensive care for thyroid disease, diabetes, obesity, and other endocrine conditions.",
    education: [
      "MD, Tanta University",
      "Endocrinology Residency, Tanta University Hospital",
      "Endocrinology Fellowship, University of Birmingham",
    ],
    certifications: [
      "Egyptian Board of Endocrinology",
      "Endocrine Society Member",
    ],
    languages: ["English", "Arabic"],
    consultationFee: 500,
    rating: 4.8,
    reviewCount: 167,
    availableToday: false,
    services: [
      "Endocrinology Consultation",
      "Diabetes Management",
      "Thyroid Disorders",
      "Weight Management",
      "Hormonal Evaluation",
    ],
  },
];
